// SEMELHANTE AO HTML E AO JAVASCRIPT, A LINGUAGEM DO REACT É A JSX

// COMO IREMOS CRIAR NOSSO PRÓPRIO COMPONENTE REACT, PRECISAMOS SEMPRE FAZER O SEGUINTE IMPORT
import React from 'react';
// IMPORTANDO COMPONENTES QUE CRIAMOS
import Main from './components/Main';
// IMPORTANDO ARQUIVO DE ESTILO DO APP
import './App.css';

// CRIANDO UMA FUNÇÃO PARA RETORNAR ALGO NO APP
// COMO O index.js ESTÁ RECEBENDO O IMPORT DO App.js, PRECISAMOS EXPORTAR ESSE COMPONENTE
// POR CONVENÇÃO, SEMPRE DEFINIMOS O NOME DA FUNÇÃO COM O MESMO NOME DO ARQUIVO
// COMPONENTES DE FUNÇÕES(SEM ESTADO) RETORNAM O JSX!!
export default function App() {
  // return <h1> Olá Mundo </h1>; // USAMOS O RETURN SEM PARENTESES QUANDO PARA RETORNAR SÓ 1 ITEM
  return <Main />;
}
